/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// const awsmobile = {
//     "aws_project_region": "us-east-1",
//     "aws_cognito_identity_pool_id": "us-east-1:31d4fd8c-aa25-44da-b126-105b20cb61b2",
//     "aws_cognito_region": "us-east-1",
//     "aws_user_pools_id": "us-east-1_P0pfG780b",
//     "aws_user_pools_web_client_id": "6dbaniehk8fdb82tq8u0261m2q",
//     "oauth": {}
// };


const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:4752f097-aa51-4d8f-b3b0-e6eb1fbe0bf9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_48XqLlL3Z",
    "aws_user_pools_web_client_id": "mtqchdin70nkp6j9kblv2lrak",
    "oauth": {}
};


export default awsmobile;
